export { HomePage } from './src/main/ets/pages/HomePage';

export { BabyPage } from './src/main/ets/pages/BabyPage';

export { AddBabyPage } from './src/main/ets/pages/AddBabyPage';

export { AddBabyLogPage } from './src/main/ets/pages/AddBabyLogPage';

export const HOME_PAGE = 'HomePage'

export const BABY_PAGE = 'BabyPage'

export const ADD_BABY_PAGE = 'AddBabyPage'

export const ADD_BABY_LOG_PAGE = 'AddBabyLogPage'