export { HomePage } from './src/main/ets/pages/HomePage';

export { BabyPage } from './src/main/ets/pages/BabyPage';

export { AddBabyPage } from './src/main/ets/pages/AddBabyPage';

export { AddBabyLogPage } from './src/main/ets/pages/AddBabyLogPage';

export { EditBabyPage } from './src/main/ets/pages/EditBabyPage';

export { HistoryPage } from './src/main/ets/pages/HistoryPage';

export { InsightsPage } from './src/main/ets/pages/InsightsPage';

export { SettingsPage } from './src/main/ets/pages/SettingsPage';

export { OnboardingPage } from './src/main/ets/pages/OnboardingPage';

export { DiaperDetailPage } from './src/main/ets/pages/DiaperDetailPage';

export * from './src/main/ets/pages/PageParams';

export const HOME_PAGE = 'HomePage'

export const BABY_PAGE = 'BabyPage'

export const ADD_BABY_PAGE = 'AddBabyPage'

export const ADD_BABY_LOG_PAGE = 'AddBabyLogPage'

export const EDIT_BABY_PAGE = 'EditBabyPage'

export const HISTORY_PAGE = 'HistoryPage'

export const INSIGHTS_PAGE = 'InsightsPage'

export const SETTINGS_PAGE = 'SettingsPage'

export const ONBOARDING_PAGE = 'OnboardingPage'

export const DIAPER_DETAIL_PAGE = 'DiaperDetailPage'
